# Generated by Django 3.1.3 on 2020-11-17 01:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Attribute',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
            ],
            options={
                'ordering': ('category__name',),
            },
        ),
        migrations.CreateModel(
            name='AttributeOption',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('attribute', models.ManyToManyField(help_text='Choice is valid for what attributes', to='materials.Attribute')),
            ],
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Material',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='MaterialAttribute',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value_type', models.CharField(choices=[('p', 'Percentage'), ('c', 'Choice')], max_length=20)),
                ('percentage', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True)),
                ('attribute', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='materials.attribute')),
                ('choice', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='materials.attributeoption')),
                ('material', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='materials.material')),
            ],
            options={
                'unique_together': {('attribute', 'material')},
            },
        ),
        migrations.CreateModel(
            name='Operand',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('attribute', 'Material Attribute'), ('operation', 'Operation'), ('text_input', 'Text Input'), ('number_input', 'Number Input'), ('null', 'Null')], max_length=20)),
                ('free_input', models.CharField(blank=True, max_length=200, null=True)),
                ('attribute', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='materials.materialattribute')),
            ],
        ),
        migrations.CreateModel(
            name='Operation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('operator', models.CharField(choices=[('ADD', 'ADD'), ('AND', 'AND'), ('OR', 'OR'), ('GT', 'GT'), ('LT', 'LT'), ('GTE', 'GTE'), ('LTE', 'LTE'), ('EQ', 'EQ'), ('NEQ', 'NEQ')], max_length=10)),
                ('left', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='left_based_operations', to='materials.operand')),
                ('right', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='right_based_operations', to='materials.operand')),
            ],
        ),
        migrations.AddField(
            model_name='operand',
            name='operation',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='materials.operation'),
        ),
        migrations.AddField(
            model_name='attribute',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='materials.category'),
        ),
    ]
